-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 13:05:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escuela` DEFAULT CHARACTER SET utf8 ;
USE `Escuela` ;

-- -----------------------------------------------------
-- Table `Escuela`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`asignatura` (
  `id_asignatura` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `horas_semana` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`id_asignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`alumno` (
  `id_alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`id_alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`departamento` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tlf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `id_director` INT NOT NULL,
  PRIMARY KEY (`id_departamento`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_departamento_profesor1_idx` (`id_director` ASC) VISIBLE,
  CONSTRAINT `fk_departamento_profesor1`
    FOREIGN KEY (`id_director`)
    REFERENCES `Escuela`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`profesor` (
  `id_profesor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `departamento_id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_profesor`, `departamento_id_departamento`),
  INDEX `fk_profesor_departamento1_idx` (`departamento_id_departamento` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_departamento1`
    FOREIGN KEY (`departamento_id_departamento`)
    REFERENCES `Escuela`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `curso` VARCHAR(45) NOT NULL,
  `letra` VARCHAR(45) NOT NULL,
  `asignatura_id_asignatura` INT NOT NULL,
  PRIMARY KEY (`id_grupo`, `asignatura_id_asignatura`),
  INDEX `fk_grupo_asignatura1_idx` (`asignatura_id_asignatura` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_asignatura1`
    FOREIGN KEY (`asignatura_id_asignatura`)
    REFERENCES `Escuela`.`asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`aula` (
  `id_aula` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NOT NULL,
  `ubicación` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`alumno_has_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`alumno_has_grupo` (
  `alumno_id_alumno` INT NOT NULL,
  `grupo_id_grupo` INT NOT NULL,
  `fecha_matriculación` DATE NOT NULL,
  `calificación` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`alumno_id_alumno`, `grupo_id_grupo`),
  INDEX `fk_alumno_has_grupo_grupo1_idx` (`grupo_id_grupo` ASC) VISIBLE,
  INDEX `fk_alumno_has_grupo_alumno_idx` (`alumno_id_alumno` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_has_grupo_alumno`
    FOREIGN KEY (`alumno_id_alumno`)
    REFERENCES `Escuela`.`alumno` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_grupo_grupo1`
    FOREIGN KEY (`grupo_id_grupo`)
    REFERENCES `Escuela`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`profesor_has_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`profesor_has_grupo` (
  `profesor_id_profesor` INT NOT NULL,
  `grupo_id_grupo` INT NOT NULL,
  PRIMARY KEY (`profesor_id_profesor`, `grupo_id_grupo`),
  INDEX `fk_profesor_has_grupo_grupo1_idx` (`grupo_id_grupo` ASC) VISIBLE,
  INDEX `fk_profesor_has_grupo_profesor1_idx` (`profesor_id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_has_grupo_profesor1`
    FOREIGN KEY (`profesor_id_profesor`)
    REFERENCES `Escuela`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesor_has_grupo_grupo1`
    FOREIGN KEY (`grupo_id_grupo`)
    REFERENCES `Escuela`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`grupo_has_aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`grupo_has_aula` (
  `grupo_id_grupo` INT NOT NULL,
  `grupo_asignatura_id_asignatura` INT NOT NULL,
  `aula_id_aula` INT NOT NULL,
  PRIMARY KEY (`grupo_id_grupo`, `grupo_asignatura_id_asignatura`, `aula_id_aula`),
  INDEX `fk_grupo_has_aula_aula1_idx` (`aula_id_aula` ASC) VISIBLE,
  INDEX `fk_grupo_has_aula_grupo1_idx` (`grupo_id_grupo` ASC, `grupo_asignatura_id_asignatura` ASC) VISIBLE,
  CONSTRAINT `fk_grupo_has_aula_grupo1`
    FOREIGN KEY (`grupo_id_grupo` , `grupo_asignatura_id_asignatura`)
    REFERENCES `Escuela`.`grupo` (`id_grupo` , `asignatura_id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_has_aula_aula1`
    FOREIGN KEY (`aula_id_aula`)
    REFERENCES `Escuela`.`aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
